### Numpy(np):Package for Multidimensional  array

In [24]:
import numpy as np # this will be the first code in any algorithm

In [2]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr)

numpy.ndarray

In [3]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [5]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(5,20) # shift+tab( for doc string)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(8) # 0 will take first value automatic/default when not assigned first value

array([0, 1, 2, 3, 4, 5, 6, 7])

In [11]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [12]:
np.arange(1,46,5) # how?

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [13]:
np.zeros(5) # default it will give float output

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(10,dtype=int) # take input as inter for output as integer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(0)

array([], dtype=float64)

In [17]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [18]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.zeros((2,5),int) # single paranthesis will not work
                       #nd  first no. row & 2nd no. column  row,column

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

##### create an array of zeros with 2 rows and 10 columns

In [20]:
np.zeros(2,10) # single paranthesis() will

TypeError: Cannot interpret '10' as a data type

In [21]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

##### see nupy videos before attending next session

In [25]:
np.linspace(0,1,5)# first no. is the starting no. and till  last no.(5) times it execute. and til middle no. it will run 
          #equal difference between the continue  no. output will be come as output

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
np.linspace(0,20,8
           )

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [27]:
np.eye(3) # it generating equal matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### # rand- gives a uniform distribution(0to 1)

In [31]:
np.random.rand(3,2) # random uniform distrinbution(0 to 1)  data of 3 rows and 2 column

array([[0.41179053, 0.49065863],
       [0.16319251, 0.74246044],
       [0.63191528, 0.74922133]])

###### randn- normal distribution(it may positive or negative also more than 1)

In [30]:
np.random.randn(3,2)

array([[ 0.89783155, -0.37504427],
       [ 0.57132779,  0.18500913],
       [ 1.43192215, -0.4428356 ]])

In [33]:
np.random.randint(34,100) # random integer.34 to 99 can not give output 100. because 100 is the last 

56

In [34]:
np.random.randint(34,100,50) # random number from (34 to 99) also no. can be repeart to full fill the 50 times and 50 item/column of number

array([47, 88, 73, 64, 79, 34, 88, 64, 43, 70, 50, 52, 86, 48, 94, 47, 52,
       60, 90, 83, 67, 51, 53, 79, 82, 53, 47, 58, 92, 51, 64, 46, 63, 52,
       84, 46, 92, 86, 45, 85, 64, 84, 62, 98, 70, 69, 35, 39, 87, 34])

In [37]:
sample_array=np.arange(30) # arange is spell as arange,colour is spell as color. arrange form 0 to 29
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [41]:
rand_array=np.random.randint(0,100,20)
rand_array

array([35, 28, 82,  2, 85, 71, 99, 28, 63, 85, 99, 51, 93, 13, 66, 19, 16,
       66, 65, 91])

In [42]:
sample_array.reshape(6,5) # in line no.37..  6 rows and 5 column

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

 ###### we highest element is 30 element . so it will only nd only procced for that type of data. nither more than 30 nor less than 30 FOR LINE 43 BELOW

In [43]:
sample_array.reshape(4,6) 

ValueError: cannot reshape array of size 30 into shape (4,6)

In [45]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [52]:
rand_array.min() # in line 41


2

In [50]:
rand_array.argmin() # argmin_- [0,1,2,3- at 3rd position min value 2 is present] index of the minimum value

3

In [53]:
sample_array.dtype # line 45.. what type of data type is integer,float etc

dtype('int32')

In [55]:
a=np.eye(5) # random intity matrix
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
a.T #Transpose of itentity matrix also same

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
a=np.random.rand(2,3)
a

array([[0.01423906, 0.21954586, 0.24811181],
       [0.39766544, 0.72205002, 0.77239961]])

In [ ]:
### a.T-- rows change in to column and column chang in rows

In [58]:
a.T  # rows change in column vice versa


array([[0.01423906, 0.39766544],
       [0.21954586, 0.72205002],
       [0.24811181, 0.77239961]])

In [61]:
sample_array=np.arange(10,21) #from 10 to 20
sample_array



array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
sample_array[3] #line 37 on index basis 3 is at 3rd plce

3

In [63]:
sample_array[3:7] # line 61 from index value 3 to 6, 7 /last index value is not consider

array([13, 14, 15, 16])

###### if have to change the value then print again the sample_array 

In [70]:
sample_array[1:4]=100  #index 1 to 3rd value will change
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [71]:
sample_array[0:7 ] # from 0 index to 6 index only


array([ 10, 100, 100, 100,  14,  15,  16])

In [72]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [75]:
subset_sample_array


array([  10, 1001, 1001, 1001,   14,   15,   16])

In [73]:
subset_sample_array[1:4]=1001 # storing in subset array
subset_sample_array



array([  10, 1001, 1001, 1001,   14,   15,   16])

In [74]:
subset_sample_array


array([  10, 1001, 1001, 1001,   14,   15,   16])

##### :(colon) it means all will be selected from index 0 to total data index

In [76]:
subset_sample_array[:]=10001
subset_sample_array

array([10001, 10001, 10001, 10001, 10001, 10001, 10001])

## Two-Dimensional array
###### index always start from 0


In [77]:
import numpy as np

In [78]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

###### index always starrt with zero(0)

In [79]:
sample_matrix[2][3] # item at row 2 and column 3 that is 7

7

In [80]:
sample_matrix[2,:] # :(colon) means all so 2nd rows with all column

array([56, 76, 24,  7])

In [81]:
sample_matrix[2] # all values of the rows will be output

array([56, 76, 24,  7])

In [82]:
sample_matrix[:,(3,2)] # all rows with column 3 and column 2. so ans will be from all rows of column 3,2

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [83]:
sample_matrix[1][3] # for 33 both style  is true

33

In [84]:
sample_matrix[1,3]

33

In [88]:
sample_matrix[0:2, 2] # how?

array([ 1, 21])

In [89]:
sample_matrix[

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [91]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [92]:
sample_array+sample_array # addition with each index

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [93]:
np.exp(sample_array) # exponential of the sample array

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [94]:
np.sqrt(sample_array)# square root of the sample array

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [95]:
np.log(sample_array)# log of the sample array

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [102]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [97]:
np.max(sample_array) # max of the sample array

19

In [99]:
np.min(sample_array)

1

In [100]:
np.argmax(sample_array)#  index of the maximmum( from 0 to start) sample array

18

In [101]:
np.argmin(sample_array)# min index always is zero

0

In [103]:
np.square(sample_array)# square of the value of sample array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [104]:
np.std(sample_array) # standard deviation

5.477225575051661

In [105]:
np.var(sample_array) #variants?

30.0

In [106]:
np.mean(sample_array)# mean

10.0

In [112]:
array=np.random.randn(3,4) # 0 to 1 random  normal distribution +ve/-ve value
array

array([[-2.86584496,  0.65041929, -0.83282886, -0.02747152],
       [ 0.24229584,  0.3830296 , -0.43362956,  0.08956981],
       [ 0.95763464, -3.09289171, -0.3146205 , -0.58750737]])

array([[ 0.31876706,  0.1032775 ,  0.40797303,  0.31067433],
       [ 0.86050785,  0.27564746,  0.02510627,  0.19233617],
       [-0.31415393,  1.9806063 , -1.35865134,  0.93765503]])

In [113]:
np.round(array,decimals=3)# after decimal 3 digit no. will be output

array([[-2.866,  0.65 , -0.833, -0.027],
       [ 0.242,  0.383, -0.434,  0.09 ],
       [ 0.958, -3.093, -0.315, -0.588]])

#### below arrange in the abcd....and last total no of the charater in the last item

In [110]:
sports=np.array(['golf','cricket','ftball','cricket','ftball','basketball'])

In [111]:
sports

array(['golf', 'cricket', 'ftball', 'cricket', 'ftball', 'basketball'],
      dtype='<U10')